project: 
  type: website
  
website: 
  title: "Evelynne Fulda"
  navbar: 
    left: 
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      
format:
  html:
    theme: minty
    css: style.css
    toc: true
    metadata:
      pagetitle: "Evelynne Fulda"