---
title: "Publications"
format: html
editor: visual
---

## 2024

1.  Karady J, Lu MT, Bergström G, Mayrhofer T, Taron J, Foldyna B, Paradis K, McCallum S, Aberg JA, Currier JS, Fitch KV, **Fulda ES**, Bloomfield GS, Overton ET, Lind L, Östgren CJ, Elvstam O, Söderberg S, Jernberg T, Pepe R, Dubé MP, Mushatt D, Fichtenbaum CJ, Malvestutto C, Zanni MV, Hoffmann U, Ribaudo H, Grinspoon SK, Douglas PS. [Coronary Plaque in People With HIV vs Non-HIV Asymptomatic Community and Symptomatic Higher-Risk Populations.](https://www.sciencedirect.com/science/article/pii/S2772963X24001534?via%3Dihub) JACC Adv.

2.  Abidi MZ, Umbleja T, Overton ET, Burdo T, Flynn JM, Lu MT, Taron J, Schnittman SR, Fitch KV, Zanni MV, Fichtenbaum CJ, Malvestutto C, Aberg JA, **Fulda ES**, Eckard AR, Manne-Goehler J, Tuan JJ, Ribaudo HJ, Douglas PS, Grinspoon SK, Brown TT, Erlandson KM. [Cytomegalovirus IgG is Associated With Physical Function But Not Muscle Density in People With HIV.](https://journals.lww.com/jaids/fulltext/2024/04150/cytomegalovirus_igg_is_associated_with_physical.10.aspx) J Acquir Immune Defic Syndr.

## 2023

1.  Lake JE, Taron J, Ribaudo HJ, Leon-Cruz J, Utay NS, Swaminathan S, Fitch KV, Kileel EM, Paradis K, **Fulda ES**, Ho KS, Luetkemeyer AF, Johnston CD, Zanni MV, Douglas PS, Grinspoon SK, Lu MT, Fichtenbaum CJ; REPRIEVE Trial Investigators. [Hepatic steatosis and nonalcoholic fatty liver disease are common and associated with cardiometabolic risk in a primary prevention cohort of people with HIV.](https://journals.lww.com/aidsonline/fulltext/2023/11150/hepatic_steatosis_and_nonalcoholic_fatty_liver.8.aspx) AIDS.

2.  Grinspoon SK, Fitch KV, Zanni MV, Fichtenbaum CJ, Umbleja T, Aberg JA, Overton ET, Malvestutto CD, Bloomfield GS, Currier JS, Martinez E, Roa JC, Diggs MR, **Fulda ES**, Paradis K, Wiviott SD, Foldyna B, Looby SE, Desvigne-Nickens P, Alston-Smith B, Leon-Cruz J, McCallum S, Hoffmann U, Lu MT, Ribaudo HJ, Douglas PS; REPRIEVE Investigators. [Pitavastatin to Prevent Cardiovascular Disease in HIV Infection.](https://www.nejm.org/doi/10.1056/NEJMoa2304146?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%20%200pubmed) N Engl J Med.

3.  Foldyna B, Mayrhofer T, Zanni MV, Lyass A, Barve R, Karady J, McCallum S, Burdo TH, Fitch KV, Paradis K, **Fulda ES**, Diggs MR, Bloomfield GS, Malvestutto CD, Fichtenbaum CJ, Aberg JA, Currier JS, Ribaudo HJ, Hoffmann U, Lu MT, Douglas PS, Grinspoon SK. [Pericoronary Adipose Tissue Density, Inflammation, and Subclinical Coronary Artery Disease Among People With HIV in the REPRIEVE Cohort.](https://academic.oup.com/cid/article/77/12/1676/7223664?login=true) Clin Infect Dis.

4.  Erlandson KM, Umbleja T, Lu MT, Taron J, Ribaudo HJ, Overton ET, Presti RM, Haas DW, Sax PE, Yin MT, Zhai BK, Louis R, Upadhyay N, Eslami P, Douglas PS, Zanni MV, Fitch KV, **Fulda ES**, Fichtenbaum CJ, Malvestutto CD, Grinspoon SK, Brown TT. [Associations of Muscle Density and Area With Coronary Artery Plaque and Physical Function.](https://journals.lww.com/jaids/fulltext/2023/10010/associations_of_muscle_density_and_area_with.11.aspx) J Acquir Immune Defic Syndr.

5.  Schnittman SR, Kitch DW, Swartz TH, Burdo TH, Fitch KV, McCallum S, Flynn JM, **Fulda ES**, Diggs MR, Stapleton JT, Casado JL, Taron J, Currier JS, Zanni MV, Malvestutto C, Fichtenbaum CJ, Aberg JA, Ribaudo HJ, Lu MT, Douglas PS, Grinspoon SK. [Coronary Artery Plaque Composition and Severity Relate to the Inflammasome in People With Treated Human Immunodeficiency Virus. Open Forum Infect Dis.](https://academic.oup.com/ofid/article/10/3/ofad106/7061296?login=true)

6.  Kolossváry M, deFilippi C, McCallum S, Fitch KV, Diggs MR, **Fulda ES**, Ribaudo HJ, Fichtenbaum CJ, Aberg JA, Malvestutto CD, Currier JS, Casado JL, Gutiérrez F, Sereti I, Douglas PS, Zanni MV, Grinspoon SK. [Identification of pre-infection markers and differential plasma protein expression following SARS-CoV-2 infection in people living with HIV.](https://www.sciencedirect.com/science/article/pii/S2352396423001032?via%3Dihub) EBioMedicine.

7.  Toribio M, Cetlin M, **Fulda ES**, Chu SM, Gómez Tejeda Zañudo J, Poteat T, Donelan K, Zanni MV. [Hormone Prescription and HIV Screening/Preventive Practices Among Clinicians Providing Care for Transgender Individuals.](https://www.liebertpub.com/doi/10.1089/trgh.2021.0118) Transgend Health.

8.  Schnittman SR, Jung W, Fitch KV, Zanni MV, McCallum S, Lee JS, Shin S, Davis BJ, **Fulda ES**, Diggs MR, Giguel F, Chinchay R, Sheth AN, Fichtenbaum CJ, Malvestutto C, Aberg JA, Currier J, Lauffenburger DA, Douglas PS, Ribaudo HJ, Alter G, Grinspoon SK. [Effect of host factors and COVID-19 infection on the humoral immune repertoire in treated HIV.](https://insight.jci.org/articles/view/166848) JCI Insight.

9.  Douglas PS, McCallum S, Lu MT, Umbleja T, Fitch KV, Foldyna B, Zanni MV, **Fulda ES**, Bloomfield GS, Fichtenbaum CJ, Overton ET, Aberg JA, Malvestutto CD, Burdo TH, Arduino RC, Ho KS, Yin MT, Ribaudo HJ, Grinspoon SK. [Ideal cardiovascular health, biomarkers, and coronary artery disease in persons with HIV.](https://journals.lww.com/aidsonline/fulltext/2023/03010/ideal_cardiovascular_health,_biomarkers,_and.6.aspx) AIDS.

10. **Fulda ES**, Fichtenbaum CJ, Kileel EM, Zanni MV, Aberg JA, Malvestutto C, Cardoso SW, Berzins B, Lira R, Harden R, Robbins G, Martinez M, Nieves SD, McCallum S, Cruz JL, Umbleja T, Sprenger H, Giguel F, Bone F, Wood K, Byroads M, Paradis K, Lu MT, Douglas PS, Ribaudo HJ, Grinspoon SK, Fitch KV; REPRIEVE Investigators. [The importance of methods for site performance evaluation in REPRIEVE, a longitudinal, global, multicenter trial.](https://www.sciencedirect.com/science/article/pii/S1551714422003615?via%3Dihub) Contemp Clin Trials.

11. Zanni MV, Foldyna B, McCallum S, Burdo TH, Looby SE, Fitch KV, **Fulda ES**, Autissier P, Bloomfield GS, Malvestutto CD, Fichtenbaum CJ, Overton ET, Aberg JA, Erlandson KM, Campbell TB, Ellsworth GB, Sheth AN, Taiwo B, Currier JS, Hoffmann U, Lu MT, Douglas PS, Ribaudo HJ, Grinspoon SK. [Sex Differences in Subclinical Atherosclerosis and Systemic Immune Activation/Inflammation Among People With Human Immunodeficiency Virus in the United States.](https://academic.oup.com/cid/article/76/2/323/6697021?login=true) Clin Infect Dis.

12. Schnittman SR, Lu MT, Mayrhofer T, Burdo TH, Fitch KV, McCallum S, **Fulda ES**, Zanni MV, Foldyna B, Malvestutto C, Fichtenbaum CJ, Aberg JA, Bloomfield GS, Overton ET, Currier J, Tebas P, Sha BE, Ribaudo HJ, Flynn JM, Douglas PS, Erlandson KM, Grinspoon SK. [Cytomegalovirus Immunoglobulin G (IgG) Titer and Coronary Artery Disease in People With Human Immunodeficiency Virus (HIV).](https://academic.oup.com/cid/article/76/3/e613/6668874?login=true)Clin Infect Dis.

## 2022

1.  Fitch KV, Fulda ES, Grinspoon SK. [Statins for primary cardiovascular disease prevention among people with HIV: emergent directions.](https://journals.lww.com/co-hivandaids/fulltext/2022/09000/statins_for_primary_cardiovascular_disease.7.aspx) Curr Opin HIV AIDS.

2.  Fitch KV, McCallum SA, Erlandson KM, Overton ET, Zanni MV, Fichtenbaum C, Aberg JA, **Fulda ES**, Kileel EM, Moran LE, Bloomfield GS, Novak RM, Pérez-Frontera S, Abrams-Downey A, Pierone G Jr, Kumarasamy N, Ruxrungtham K, Mngqibisa R, Douglas PS, Ribaudo HJ, Grinspoon SK. [Diet in a global cohort of adults with HIV at low-to-moderate traditional cardiovascular disease risk.](https://journals.lww.com/aidsonline/fulltext/2022/11150/diet_in_a_global_cohort_of_adults_with_hiv_at.11.aspx) AIDS.

3.  Kolossváry M, deFilippi C, Lu MT, Zanni MV, **Fulda ES**, Foldyna B, Ribaudo H, Mayrhofer T, Collier AC, Bloomfield GS, Fichtenbaum C, Overton ET, Aberg JA, Currier J, Fitch KV, Douglas PS, Grinspoon SK. [Proteomic Signature of Subclinical Coronary Artery Disease in People With HIV: Analysis of the REPRIEVE Mechanistic Substudy.](https://academic.oup.com/jid/article/226/10/1809/6583088?login=true) J Infect Dis.

4.  Looby SE, Kantor A, Burdo TH, Currier JS, Fichtenbaum CJ, Overton ET, Aberg JA, Malvestutto CD, Bloomfield GS, Erlandson KM, Cespedes M, Kallas EG, Masiá M, Thornton AC, Smith MD, Flynn JM, Kileel EM, **Fulda E**, Fitch KV, Lu MT, Douglas PS, Grinspoon SK, Ribaudo HJ, Zanni MV. [Factors Associated With Systemic Immune Activation Indices in a Global Primary Cardiovascular Disease Prevention Cohort of People With Human Immunodeficiency Virus on Antiretroviral Therapy.](https://academic.oup.com/cid/article/75/8/1324/6541259?login=true) Clin Infect Dis.

5.  Erlandson KM, Fitch KV, McCallum SA, Ribaudo HJ, Overton ET, Zanni MV, Bloomfield GS, Brown TT, Fichtenbaum CJ, Bares S, Aberg JA, Douglas PS, **Fulda ES**, Santana-Bagur JL, Castro JG, Moran LE, Mave V, Supparatpinyo K, Ponatshego PL, Schechter M, Grinspoon SK. [Geographical Differences in the Self-Reported Functional Impairment of People With Human Immunodeficiency Virus (HIV) and Associations With Cardiometabolic Risk.](https://academic.oup.com/cid/article/75/7/1154/6528571?login=true) Clin Infect Dis.

6.  **Fulda ES**, Fitch KV, Overton ET, Zanni MV, Aberg JA, Currier JS, Lu MT, Malvestutto C, Fichtenbaum CJ, Martinez E, Umbleja T, Douglas PS, Ribaudo HJ, Grinspoon SK. [COVID-19 Vaccination Rates in a Global HIV Cohort.](https://academic.oup.com/jid/article/225/4/603/6431673?login=true) J Infect Dis.

## 2021

1.  Cetlin M, **Fulda ES**, Chu SM, Hamnvik OR, Poteat T, Zanni MV, Toribio M. [Cardiovascular Disease Risk Among Transgender People with HIV.](https://link.springer.com/article/10.1007/s11904-021-00572-z) Curr HIV/AIDS Rep.

2.  Toribio M, **Fulda ES**, Chu SM, Drobni ZD, Awadalla M, Cetlin M, Stanley TL, North CM, Nelson MD, Jerosch-Herold M, Szczepaniak LS, Burdo TH, Looby SE, Neilan TG, Zanni MV. [Hot Flashes and Cardiovascular Disease Risk Indices Among Women With HIV.](https://academic.oup.com/ofid/article/8/2/ofab011/6089172?login=true) Open Forum Infect Dis.

## 2020

1.  Toribio M, Burdo TH, **Fulda ES**, Cetlin M, Chu SM, Feldpausch MN, Robbins GK, Neilan TG, Melbourne K, Grinspoon SK, Zanni MV. [Effects of Integrase Inhibitor-Based ART on the NLRP3 Inflammasome Among ART-Naïve People With HIV.](https://academic.oup.com/ofid/article/7/10/ofaa459/5913169?login=true) Open Forum Infect Dis.

2.  Toribio M, Awadalla M, Cetlin M, **Fulda ES**, Stanley TL, Drobni ZD, Szczepaniak LS, Nelson MD, Jerosch-Herold M, Burdo TH, Neilan TG, Zanni MV. [Brief Report: Vascular Dysfunction and Monocyte Activation Among Women With HIV.](https://journals.lww.com/jaids/fulltext/2020/10010/brief_report__vascular_dysfunction_and_monocyte.16.aspx) J Acquir Immune Defic Syndr.
